---
grails:
    profile: web
    codegen:
        defaultPackage: fiscalizacionne
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    cors:
        enabled: true
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    plugin:
        databasemigration:
            changelogFileName: changelog.xml
    mail:
        host: smtp.gmail.com
        port: 465
        username: ne.elecciones.test@gmail.com
        password: macrigato1234
        disabled: false
        props:
            mail:
                smtp:
                    auth: true
                    socketFactory:
                        port: 465
                        class: javax.net.ssl.SSLSocketFactory
                        fallback: false
                    starttls:
                        enable: true
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''

environments:
    development:
        dataSource:
          driverClassName: com.mysql.jdbc.Driver
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          url: jdbc:mysql://127.0.0.1:3306/elecciones?useUnicode=yes&characterEncoding=UTF-8
          username: fiscalizacionne
          password: elpepefueunrevolucionario

    test:
        dataSource:
          driverClassName: com.mysql.jdbc.Driver
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          url: jdbc:mysql://127.0.0.1:3306/elecciones?useUnicode=yes&characterEncoding=UTF-8
          username: fiscalizacionne
          password: elpepefueunrevolucionario

    production:
        dataSource:
          driverClassName: com.mysql.jdbc.Driver
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          url: jdbc:mysql://127.0.0.1:3306/elecciones?useUnicode=yes&characterEncoding=UTF-8
          username: fiscalizacionne
          password: elpepefueunrevolucionario
          properties:
              jmxEnabled: true
              initialSize: 5
              maxActive: 50
              minIdle: 5
              maxIdle: 25
              maxWait: 10000
              maxAge: 600000
              timeBetweenEvictionRunsMillis: 5000
              minEvictableIdleTimeMillis: 60000
              validationQuery: SELECT 1
              validationQueryTimeout: 3
              validationInterval: 15000
              testOnBorrow: true
              testWhileIdle: true
              testOnReturn: false
              jdbcInterceptors: ConnectionState
              defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
        grails:
          mail:
            host: smtp.gmail.com
            port: 465
            username: fti.nuevoencuentro@gmail.com
            password: unidadciudadana2017
            disabled: false
            props:
              mail:
                smtp:
                  auth: true
                  socketFactory:
                    port: 465
                    class: javax.net.ssl.SSLSocketFactory
                    fallback: false
                  starttls:
                    enable: true

